conditioning:
  method: CoDPS
  params:
    scale: 0.01
    t_div: 100
    div_ratio: 10
    inv_var: 0.1
    use_A_AT: True

data:
  name: ffhq
  root: ./samples/ffhq_00000_256/

measurement:
  operator:
    name: super_resolution
    scale_factor: 4
    degradation: gaussian # or bicubic, avg_pool degradation types 
  
  noise: 
    name: gaussian
    sigma: 0.05
