conditioning:
  method: CoDPS+
  params:
    scale: 0.05
    t_div: 15
    div_ratio: 10
    inv_var: 1
    use_A_AT: True


data:
  name: ffhq
  root: ./samples/ffhq_00000_256/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3
  
  noise: 
    name: gaussian
    sigma: 0.05
